### ISSUE TITLE
building on Python 3.9 on GitHub actions

### ISSUE THREAD

**Issue by krober10nd** [dengwirda/inpoly-python#11]
* When trying to build I get this catch22/circular dependency on numpy however in my setup.cfg file I list `numpy` prior to `inpoly`. 

```
Collecting inpoly
50
  Downloading inpoly-0.1.2.tar.gz (185 kB)
51
    ERROR: Command errored out with exit status 1:
52
     command: /home/runner/work/oceanmesh/oceanmesh/.tox/py3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xvjq0yr3/inpoly_0ed7e6adff01462d9847c040b32eb64e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xvjq0yr3/inpoly_0ed7e6adff01462d9847c040b32eb64e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-d9j1ovqu
53
         cwd: /tmp/pip-install-xvjq0yr3/inpoly_0ed7e6adff01462d9847c040b32eb64e/
54
    Complete output (5 lines):
55
    Traceback (most recent call last):
56
      File "<string>", line 1, in <module>
57
      File "/tmp/pip-install-xvjq0yr3/inpoly_0ed7e6adff01462d9847c040b32eb64e/setup.py", line 6, in <module>
58
        import numpy as np
59
    ModuleNotFoundError: No module named 'numpy'
```

**Comment by krober10nd** [comment]
This does not happen on other versions of Python < 3.9 oddly enough.
